### ISSUE TITLE
Modification needed (For initial page load)

### ISSUE THREAD

**Issue by polakDas** [JubairRahman/Markdown-Badges#2]
There are so many links in the `README.md` file. For that reason, your repository takes much time to load initially. I think it's better to separate sections in other `.md` file and link them.

**Comment by JubairRahman** [comment]
I didn't get your point brother...

**Comment by polakDas** [comment]
When I'm trying to visit this repository, it takes around 5-10 second to load the page. Sometimes it's more than 10 second. This is because of the links of the badges. There are so many badges in your `README.md` file. You better separate them in other `.md` files. Like AI related badge should go in the `AI.md` file. Then link the  `AI.md` file to your `README.md` file. It'll decrease the initial page load time.

**Comment by JubairRahman** [comment]
Got it, Thank you, brother. Keep in touch....
